# Generated by Django 3.2.4 on 2021-07-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210701_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='extra_detail',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
